steps:
  - name: maven:3.6.0-jdk-11-slim
    entrypoint: mvn
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/coronavirustracker-272506', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', '--image', 'gcr.io/$PROJECT_ID/coronavirustracker-272506', '--platform', 'managed']
images: ['gcr.io/$PROJECT_ID/coronavirustracker-272506']